FROM ocaml/opam:ubuntu-16.04_ocaml-4.04.0

ENV OPAM_PKGS ocamlfind ocamlbuild oasis core_kernel menhir cmdliner yojson ounit
USER opam
ENV TERM xterm
ADD . ez
RUN sudo chown -R opam.nogroup /home/opam/ez
WORKDIR /home/opam/ez

# RUN opam update -u && \
#     opam config exec -- opam-depext $OPAM_PKGS

RUN opam config exec -- opam install $OPAM_PKGS
RUN opam config exec -- make configure
RUN opam config exec -- make
